[workspace]
members = [
    "cssh-rs",
    "cssh-rs-core",
    "cssh-rs-meta",
    "cssh-rs-platform",
    "cssh-rs-platform-linux",
    "cssh-rs-platform-macos",
    "cssh-rs-platform-windows",
    "cssh-rs-protocol",
    "xtask",
]
resolver = "2"

[profile.release]
opt-level = "z"   # Optimize for size.
lto = true
codegen-units = 1
