order = ["security", "feature", "bugfix", "deprecation", "removal"]

[context]
name = "cssh-rs"
version = "0.19.1"
url = "https://github.com/whmade/cssh-rs"

[paths]
directory = "news"

[types]
security = "Security"
feature = "Features"
bugfix = "Bug Fixes"
deprecation = "Deprecations"
removal = "Removals"
