[package]
name = "cssh-rs-protocol"
version.workspace = true
edition = "2021"
license-file = "../LICENSE.txt"

[dependencies]
serde = "1.0.228"
serde_derive = "1.0.228"
serde_bytes = "0.11.19"
ciborium = "0.2.2"
thiserror = "2.0.18"

[dependencies.windows]
version = "0.62.2"
features = ["Win32_System_Console"]

[dev-dependencies]
insta = "1.43"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage,coverage_nightly)'] }
